### ISSUE TITLE
vcs seg fault on ubuntu 16.04 using regular not nox vtk 

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#116]
gdb --args python /export/doutriaux1/git/uvcdat/testing/vcs/test_vcs_basic_gms.py --gm_type=isofill --projection=-3 --lat1=-90 --lat2=0 --lon1=-180 --lon2=180 --range_via_gm --source=/export/doutriaux1/git/build_uvcdat/uvcdat-testdata/baselines/vcs/test_vcs_basic_isofill_-3_proj_SH_-180_180_via_gm.png
```
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-90.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/bin/python...done.
(gdb) r
Starting program: /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/bin/python /export/doutriaux1/git/uvcdat/testing/vcs/test_vcs_basic_gms.py --gm_type=isofill --projection=-3 --lat1=-90 --lat2=0 --lon1=-180 --lon2=180 --range_via_gm --source=/export/doutriaux1/git/build_uvcdat/uvcdat-testdata/baselines/vcs/test_vcs_basic_isofill_-3_proj_SH_-180_180_via_gm.png
Program received signal SIGSEGV, Segmentation fault.
0x00000030d5a8ac46 in __rawmemchr_sse2 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install elfutils-libelf-0.164-2.el6.x86_64 glibc-2.12-1.192.el6.x86_64 libICE-1.0.6-1.el6.x86_64 libSM-1.2.1-2.el6.x86_64 libX11-1.6.3-2.el6.x86_64 libXau-1.0.6-4.el6.x86_64 libXdamage-1.1.3-4.el6.x86_64 libXext-1.3.3-1.el6.x86_64 libXfixes-5.0.1-2.1.el6.x86_64 libXt-1.1.4-6.1.el6.x86_64 libXxf86vm-1.1.3-2.1.el6.x86_64 libdrm-2.4.65-2.el6.x86_64 libgcc-4.4.7-17.el6.x86_64 libgomp-4.4.7-17.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libstdc++-4.4.7-17.el6.x86_64 libuuid-2.17.2-12.24.el6_8.1.x86_64 libxcb-1.11-2.el6.x86_64 mesa-dri-drivers-11.0.7-4.el6.x86_64 mesa-libGL-11.0.7-4.el6.x86_64 mesa-private-llvm-3.6.2-1.el6.x86_64
(gdb) bt
#0  0x00000030d5a8ac46 in __rawmemchr_sse2 () from /lib64/libc.so.6
#1  0x00000030d5a756d0 in _IO_str_init_static_internal () from /lib64/libc.so.6
#2  0x00000030d5a69675 in vsscanf () from /lib64/libc.so.6
#3  0x00000030d5a636e8 in sscanf () from /lib64/libc.so.6
#4  0x00007fff738cb399 in vtkOpenGLExtensionManager::ReadOpenGLExtensions() ()
   from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingOpenGL-7.1.so.1
#5  0x00007fff738ca800 in vtkOpenGLExtensionManager::Update() ()
   from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingOpenGL-7.1.so.1
#6  0x00007fff738ca577 in vtkOpenGLExtensionManager::ExtensionSupported(char const*) ()
   from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingOpenGL-7.1.so.1
#7  0x00007fff738eb42a in vtkOpenGLRenderWindow::OpenGLInitContext() ()
   from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingOpenGL-7.1.so.1
#8  0x00007fff738e8a6d in vtkOpenGLRenderWindow::OpenGLInit() ()
   from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingOpenGL-7.1.so.1
#9  0x00007fff738e97ac in vtkOpenGLRenderWindow::CreateHardwareOffScreenWindow(int, int) ()
   from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingOpenGL-7.1.so.1
#10 0x00007fff73967932 in vtkXOpenGLRenderWindow::CreateOffScreenWindow(int, int) ()
   from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingOpenGL-7.1.so.1
#11 0x00007fff7396402d in vtkXOpenGLRenderWindow::Start() ()
   from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingOpenGL-7.1.so.1
#12 0x00007fff8249a4f6 in vtkRenderWindow::DoStereoRender() ()
   from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingCore-7.1.so.1
#13 0x00007fff8249aa7b in vtkRenderWindow::DoFDRender() () from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingCore-7.1.so.1
#14 0x00007fff8249bb35 in vtkRenderWindow::DoAARender() () from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingCore-7.1.so.1
#15 0x00007fff8249abad in vtkRenderWindow::Render() () from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingCore-7.1.so.1
#16 0x00007fff739646d1 in vtkXOpenGLRenderWindow::Render() ()
   from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingOpenGL-7.1.so.1
#17 0x00007fff73c46789 in PyvtkXOpenGLRenderWindow_Render(_object*, _object*) ()
   from /export/doutriaux1/anaconda2/envs/v2.8-2-g42af3f9/lib/python2.7/site-packages/vtk/../../../libvtkRenderingOpenGLPython27D-7.1.so.1
#18 0x00007ffff7ce9bf1 in call_function (f=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:4350
#19 PyEval_EvalFrameEx (f=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:2987
#20 0x00007ffff7cec99d in PyEval_EvalCodeEx (co=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:3582
#21 0x00007ffff7c63df5 in function_call (func=0x7fff6724ab18, arg=0x7fff67044590, kw=0x7fff66e64c58) at Objects/funcobject.c:523
#22 0x00007ffff7c31e33 in PyObject_Call (func=0x7fff6724ab18, arg=Unhandled dwarf expression opcode 0xf3
) at Objects/abstract.c:2546
#23 0x00007ffff7ce76af in ext_do_call (f=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:4664
#24 PyEval_EvalFrameEx (f=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:3026
#25 0x00007ffff7cec99d in PyEval_EvalCodeEx (co=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:3582
#26 0x00007ffff7ce95f7 in fast_function (f=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:4445
#27 call_function (f=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:4370
#28 PyEval_EvalFrameEx (f=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:2987
#29 0x00007ffff7cec99d in PyEval_EvalCodeEx (co=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:3582
#30 0x00007ffff7ce95f7 in fast_function (f=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:4445
#31 call_function (f=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:4370
#32 PyEval_EvalFrameEx (f=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:2987
#33 0x00007ffff7cec99d in PyEval_EvalCodeEx (co=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:3582
#34 0x00007ffff7cecad2 in PyEval_EvalCode (co=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:669
#35 0x00007ffff7d156f2 in run_mod (fp=0x6a7ab0, filename=Unhandled dwarf expression opcode 0xf3
) at Python/pythonrun.c:1376
#36 PyRun_FileExFlags (fp=0x6a7ab0, filename=Unhandled dwarf expression opcode 0xf3
) at Python/pythonrun.c:1362
#37 0x00007ffff7d16a89 in PyRun_SimpleFileExFlags (fp=0x6a7ab0, filename=0x7fffffffe42f "/export/doutriaux1/git/uvcdat/testing/vcs/test_vcs_basic_gms.py", closeit=1, 
    flags=0x7fffffffdee0) at Python/pythonrun.c:948
#38 0x00007ffff7d2c70d in Py_Main (argc=Unhandled dwarf expression opcode 0xf3
) at Modules/main.c:640
#39 0x00000030d5a1ed1d in __libc_start_main () from /lib64/libc.so.6
#40 0x0000000000400701 in _start ()
(gdb) 
```

**Comment by aashish24** [comment]
@doutriaux1 is this still a problem? I thought we fixed the issues for non-vmc, non-remote rendering setup.

**Comment by doutriaux1** [comment]
@aashish24 just installed a fresh nightly i get:
```
>>> import vcs
>>> x=vcs.init()
>>> x.plot([1,2,3,4,56])
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  52
  Current serial number in output stream:  53
```

**Comment by danlipsa** [comment]
@doutriaux1 The new mesa (17.0.3) works well on Linux with few failures I addressed in:
https://github.com/UV-CDAT/vcs/pull/176. I'll close this ...

**Comment by doutriaux1** [comment]
@danlipsa

**Comment by danlipsa** [comment]
@doutriaux1 Did you try any of the solutions in
https://askubuntu.com/questions/654566/steam-doesnt-start-libgl-error
The problem they are seeing seems similar with yours.

**Comment by doutriaux1** [comment]
```
export LD_PRELOAD='/usr/lib/x86_64-linux-gnu/libstdc++.so.6'
```
fixes this for me
