### ISSUE TITLE
meshfill broken

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#135]
@sankhesh your commit 5f393f1958e74db79a8b8c64817382a8f431d3fc introduced the bug.

Please to reproduce run test:
```
(2.8) doutriaux1@maryam:[vcs]:[9635]> python /git/uvcdat/testing/vcs/test_vcs_plot_unstructured_via_boxfill.py fdfdf
Traceback (most recent call last):
  File "/git/uvcdat/testing/vcs/test_vcs_plot_unstructured_via_boxfill.py", line 6, in <module>
    x.plot(s,bg=1)
  File "/Users/doutriaux1/anaconda2/envs/2.8/lib/python2.7/site-packages/vcs/Canvas.py", line 2564, in plot
    a = self.__plot(arglist, keyargs)
  File "/Users/doutriaux1/anaconda2/envs/2.8/lib/python2.7/site-packages/vcs/Canvas.py", line 3893, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/Users/doutriaux1/anaconda2/envs/2.8/lib/python2.7/site-packages/vcs/VTKPlots.py", line 607, in plot
    vtk_backend_grid, vtk_backend_geo, **kargs))
  File "/Users/doutriaux1/anaconda2/envs/2.8/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 317, in plot
    self._plotInternal()
  File "/Users/doutriaux1/anaconda2/envs/2.8/lib/python2.7/site-packages/vcs/vcsvtk/meshfillpipeline.py", line 186, in _plotInternal
    c = self.getColorIndexOrRGBA(_colorMap, tmpColors[ct][0])
IndexError: list index out of range
```

**Comment by doutriaux1** [comment]
I recommend the fix to be implemented in branch: `migrate_test_suite`
the tests that exhibit this bug are in directory: `tests/failing`

**Comment by doutriaux1** [comment]
`master` has bugs that have been introduced by @chaosphere2112 PR #131

**Comment by doutriaux1** [comment]
@sankhesh  any progress on this?

**Comment by sankhesh** [comment]
@doutriaux1 I haven't had a chance to look into this yet. If its not urgent, mind if I look into it tomorrow? Thanks!

**Comment by doutriaux1** [comment]
@sankhesh tomorrw is totally fine.

**Comment by doutriaux1** [comment]
@sankhesh we really need this in soon now!

**Comment by sankhesh** [comment]
@doutriaux1 Working on this now.
