### ISSUE TITLE
VTK bugs before release

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#163]
beside the failed vtk_ui test i now get this one (mac as well):

```
vtk-cdat-nox              7.1.0.2017.3.23.73fb094d17ccdd594a6abf9ff8732149c88dc2e6          py27_0    uvcdat
```

test error log:

```
Failed test: test_vcs_put_png_on_canvas on Thu Mar 30 11:34:12 2017
Log

E
======================================================================
ERROR: testPutPng (test_vcs_put_png_on_canvas.TestVCSPNG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/git/vcs/tests/test_vcs_put_png_on_canvas.py", line 19, in testPutPng
    self.putPNGOnCanvas()
  File "/git/vcs/tests/test_vcs_put_png_on_canvas.py", line 13, in putPNGOnCanvas
    self.x.put_png_on_canvas(self.png,zoom,xoffset,yoffset,units,fitToHeight,bg=self.bg)
  File "/git/vcs/vcs/Canvas.py", line 4923, in put_png_on_canvas
    **kargs)
  File "/git/vcs/vcs/VTKPlots.py", line 967, in put_png_on_canvas
    filename, zoom, xOffset, yOffset, units, fitToHeight, *args, **kargs)
  File "/git/vcs/vcs/VTKPlots.py", line 975, in put_img_on_canvas
    reader.SetFileName(filename)
AttributeError: 'NoneType' object has no attribute 'SetFileName'

----------------------------------------------------------------------
Ran 1 test in 0.042s

FAILED (errors=1)
```

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Not a VTK bug:
The problem is that:
/home/danlipsa/anaconda2/envs/nightly-20170407/share/uvcdat/sample_data/BlueMarble.ppm
is missing
so it needs to be added in 
Share/test_data_files.txt

I'll let you @doutriaux1 to do this and close this bug when you are done. Thanks! I am not sure how to do this.

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa I updated the description.

**Comment by doutriaux1** [comment]
@danlipsa nice catch. Will add it today.

**Comment by doutriaux1** [comment]
@danlipsa can I fix it in your PR?

**Comment by aashish24** [comment]
@doutriaux1 I think it would be much cleaner if you push a separate PR for it..
