### ISSUE TITLE
no_legend template does not have the viewport set

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/vcs#227]
The following script crashes in vcs nightly. It used to work about a year ago when I worked last at vcs.js

```python
import vcs
import cdms2

f=cdms2.open('coads_climatology.nc')
s=f('SST')

x=vcs.init()
gm=x.createisofill()
p = x.createprojection()
p.type = 'robinson'
gm.projection=p

x.plot(s, 'no_legend', gm, ratio="autot")
x.png('test.png')
```

Currently, it prints the following:
<pre>
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    x.plot(s, 'no_legend', gm, ratio="autot")
  File "/home/danlipsa/anaconda2/envs/nightly-20170711/lib/python2.7/site-packages/vcs/Canvas.py", line 2690, in plot
    a = self.__plot(arglist, keyargs)
  File "/home/danlipsa/anaconda2/envs/nightly-20170711/lib/python2.7/site-packages/vcs/Canvas.py", line 4019, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/home/danlipsa/anaconda2/envs/nightly-20170711/lib/python2.7/site-packages/vcs/VTKPlots.py", line 680, in plot
    vtk_backend_grid, vtk_backend_geo, **kargs))
  File "/home/danlipsa/anaconda2/envs/nightly-20170711/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 326, in plot
    self._plotInternal()
  File "/home/danlipsa/anaconda2/envs/nightly-20170711/lib/python2.7/site-packages/vcs/vcsvtk/isofillpipeline.py", line 191, in _plotInternal
    self._gm, t, z, **kwargs))
  File "/home/danlipsa/anaconda2/envs/nightly-20170711/lib/python2.7/site-packages/vcs/VTKPlots.py", line 866, in renderTemplate
    displays = tmpl.plot(self.canvas, data, gm, bg=self.bg, X=X, Y=Y, **kargs)
  File "/home/danlipsa/anaconda2/envs/nightly-20170711/lib/python2.7/site-packages/vcs/template.py", line 1749, in plot
    **kargs)
  File "/home/danlipsa/anaconda2/envs/nightly-20170711/lib/python2.7/site-packages/vcs/template.py", line 1040, in drawTicks
    dx = dx / (vp[1] - vp[0])
ZeroDivisionError: float division by zero
</pre>

**Comment by danlipsa** [comment]
@doutriaux1 Any ideas?

**Comment by doutriaux1** [comment]
somehow our viewport has the same vp[0] and vp[1] i.e it's null. where does the `no_legend` template comes from?

**Comment by doutriaux1** [comment]
@danlipsa `autot` should do nothing for projected plots, is that the culprit? Did we mess anything and we are now going into the `autot` code?

**Comment by danlipsa** [comment]
@doutriaux1 That's what I thought initially, but it crashes without autot as well. Not sure where 'no_legend' comes from. Its a standard template in vcs.

**Comment by doutriaux1** [comment]
```python
import basevcstest
import cdms2

class VCSTestNoLegTemplate(basevcstest.VCSBaseTest):
    def test_no_leg(self):
        f = cdms2.open('http://test.opendap.org/opendap/hyrax/data/nc/coads_climatology.nc')
        gm=self.x.createisofill()
        p = self.x.createprojection()
        p.type = 'robinson'
        gm.projection=p

        self.x.plot(f("SST"), 'no_legend', gm, ratio="autot")
```

works for me
~
