### ISSUE TITLE
Plotting CCSM4 areacello data fails

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/vcs#64]
The offending file is:
`/cmip5_css02/scratch/cmip5/output1/NCAR/CCSM4/1pctCO2/fx/ocean/fx/r0i0p0/v20130312/areacello/areacello_fx_CCSM4_1pctCO2_r0i0p0.nc`

``` python
/work/cmip5/fx/fx/areacello/cmip5.CCSM4.1pctCO2.r0i0p0.fx.ocn.fx.areacello.ver-v20130312.latestX.xml
Traceback (most recent call last):
  File "make_evsp.py", line 171, in <module>
    c.plot(areacello)
  File "/usr/local/uvcdat/2016-02-04/lib/python2.7/site-packages/vcs/Canvas.py", line 2424, in plot
    a = self.__plot(arglist, keyargs)
  File "/usr/local/uvcdat/2016-02-04/lib/python2.7/site-packages/vcs/Canvas.py", line 3747, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/usr/local/uvcdat/2016-02-04/lib/python2.7/site-packages/vcs/VTKPlots.py", line 533, in plot
    vtk_backend_grid, vtk_backend_geo))
  File "/usr/local/uvcdat/2016-02-04/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 290, in plot
    self._createMaskedDataMapper()
  File "/usr/local/uvcdat/2016-02-04/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 335, in _createMaskedDataMapper
    deep=False)
  File "/usr/local/uvcdat/2016-02-04/lib/python2.7/site-packages/vcs/vcs2vtk.py", line 117, in putMaskOnVTKGrid
    vtkmask.SetNumberOfTuples(attributes2.GetPedigreeIds().GetNumberOfTuples())
AttributeError: 'NoneType' object has no attribute 'GetNumberOfTuples'
```

The equivalent plot in ferret looks like:
![cmip5 ccsm4 1pctco2 r0i0p0 fx ocn fx areacello ver-v20130312](https://cloud.githubusercontent.com/assets/3229632/13095083/05e4ca70-d4c4-11e5-8528-e34d3768f0de.gif)

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1833

**Comment by durack1** [comment]
@chaosphere2112 @doutriaux1 here too

**Comment by durack1** [comment]
@danlipsa this issue is still a problem with `2.10-rc2` the latest `master`. @doutriaux1 is this solve-able for `v2.10.0`?
Ferret:
![cmip5 mri-cgcm3 rcp60 r0i0p0 fx ocn fx basin ver-v20111215 latestx warn2](https://cloud.githubusercontent.com/assets/3229632/24382878/1410eece-130e-11e7-8fff-60601986f1ff.gif)
CDAT:
![cmip5 mri-cgcm3 1pctco2 r0i0p0 fx ocn fx basin ver-v20110831 latestx](https://cloud.githubusercontent.com/assets/3229632/24382882/19c39a1a-130e-11e7-8d88-2d3c0525e387.png)

**Comment by doutriaux1** [comment]
@durack1 I don't think we addressed this at all in this version.

**Comment by durack1** [comment]
@doutriaux1 @williams13 there are a bunch of open issues that really would be nice to get sorted before the `v2.10` release, I know you're pushing hard on getting things locked down before the end of this month, but I think a better product is more important than a faster (buggy) product.. Having said that I suppose `v3.0` is around the corner too

**Comment by durack1** [comment]
@doutriaux1 @danlipsa some more examples:
Ferret:
![cmip5 access1-0 1pctco2 r0i0p0 fx ocn fx areacello ver-1](https://cloud.githubusercontent.com/assets/3229632/24424520/bed4a25e-13b5-11e7-8c71-df709db2645c.gif)
and CDAT:
![cmip5 access1-0 1pctco2 r0i0p0 fx ocn fx areacello ver-1](https://cloud.githubusercontent.com/assets/3229632/24424532/c4cc86a4-13b5-11e7-94d0-e9340d6a11cb.png)

**Comment by doutriaux1** [comment]
@durack1 if you want the `ferret` version plot `data.filled()` it will lose dim information and will plot a straight numpy array just like `ferret`

**Comment by durack1** [comment]
@doutriaux1 my point of the examples above was that ferret appears to plot things correctly, so land (for areacello) is missing or zero, and the ocean points  only have values.. For vcs it doesn't do that..

**Comment by durack1** [comment]
@danlipsa @aashish24 @doutriaux1 @dnadeau4 I have a heap of these data in a couple of `tar.bz2` archives, it would be great to centralize these so that you all have access to the data plotted above that is causing the problems
```
-rw-r--r--  1 durack1 climate  19M Feb 16  2012 120216_ipcc5_tas_Amon.tar.bz2
-rw-r--r--  1 durack1 climate 377M Feb 28  2012 120218_ipcc5_so_Omon.tar.bz2
```
Ping me if you want these dropped on a webserver to add to a test suite.. I've also got some of the CMIP6 test grids to play with, and have requested more

**Comment by durack1** [comment]
@doutriaux1 @danlipsa I really think this should be up on the high priority fix list for the next release, I have just tried to plot the vanilla variable `tos` from a suite of models, and the first four I plotted looked like this:
![cmip5 access1-0 1pctco2 r1i1p1 mo ocn omon tos ver-1](https://cloud.githubusercontent.com/assets/3229632/25361863/6459cd9e-2905-11e7-85dc-81e707a50b81.png)
![cmip5 access1-3 1pctco2 r1i1p1 mo ocn omon tos ver-1](https://cloud.githubusercontent.com/assets/3229632/25361864/66858252-2905-11e7-952b-38a76a2ccd72.png)
![cmip5 ccsm4 1pctco2 r1i1p1 mo ocn omon tos ver-v20121128](https://cloud.githubusercontent.com/assets/3229632/25361865/686774c2-2905-11e7-990c-4576be458a1e.png)
![cmip5 cesm1-bgc 1pctco2 r1i1p1 mo ocn omon tos ver-v20140822](https://cloud.githubusercontent.com/assets/3229632/25361867/6a49c970-2905-11e7-81c2-ef706f8fc5ce.png)
That is to say, everyone of them was plotted incorrectly
