### ISSUE TITLE
[VCS] x.plot(variable) fails with poorly defined bounds

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/vcs#74]
This issue is reproducible:

``` python
>>> type(soAnom)
<class 'cdms2.tvariable.TransientVariable'>
>>> soAnom.shape
(50, 50, 300, 360)
>>> soAnom.getAxisIds()
['time', 'st_ocean', 'yt_ocean', 'xt_ocean']
>>> x = vcs.init()
>>> x.plot(soAnom[0,0,])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/uvcdat/2.4.0rc1/lib/python2.7/site-packages/vcs/Canvas.py", line 2524, in plot
    a = self.__plot(arglist, keyargs)
  File "/usr/local/uvcdat/2.4.0rc1/lib/python2.7/site-packages/vcs/Canvas.py", line 3628, in __plot
    arglist[0] = self._reconstruct_tv(arglist, keyargs)
  File "/usr/local/uvcdat/2.4.0rc1/lib/python2.7/site-packages/vcs/Canvas.py", line 757, in _reconstruct_tv
    mesh = grid.getMesh()
  File "/usr/local/uvcdat/2.4.0rc1/lib/python2.7/site-packages/cdms2/hgrid.py", line 236, in getMesh
    raise CDMSError, 'No boundary data is available for grid %s'%self.id
cdms2.error.CDMSError: No boundary data is available for grid grid_4
```

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1590

**Comment by doutriaux1** [comment]
potential data: http://aims3.llnl.gov/thredds/fileServer/cmip5_css01_data/cmip5/output1/BCC/bcc-csm1-1-m/piControl/fx/ocean/fx/r0i0p0/v20130307/areacello/areacello_fx_bcc-csm1-1-m_piControl_r0i0p0.nc
